name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: Modinstaller2/bin/Modinstaller2/Release/netcoreapp3.1/win-x64/publish
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -r linux-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: Modinstaller2/bin/Modinstaller2/Release/netcoreapp3.1/linux-x64/publish
